# Generated by Django 6.0.2 on 2026-05-20 08:04

import FYP_app.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FYP_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='credentials',
            options={'verbose_name': 'Credential', 'verbose_name_plural': 'Credentials'},
        ),
        migrations.RenameField(
            model_name='credentials',
            old_name='Nominee',
            new_name='assigned_nominee',
        ),
        migrations.RenameField(
            model_name='credentials',
            old_name='Email',
            new_name='email_on_platform',
        ),
        migrations.RenameField(
            model_name='credentials',
            old_name='Password',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='credentials',
            old_name='Platform',
            new_name='platform',
        ),
        migrations.RenameField(
            model_name='credentials',
            old_name='Platform_URL',
            new_name='platform_url',
        ),
        migrations.RenameField(
            model_name='credentials',
            old_name='UserName',
            new_name='username_on_platform',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='last_heartbeat',
            new_name='last_seen',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='heartbeat_interval',
            new_name='timeout_days',
        ),
        migrations.RemoveField(
            model_name='user',
            name='DOB',
        ),
        migrations.RemoveField(
            model_name='user',
            name='Gender',
        ),
        migrations.AlterField(
            model_name='chatmemory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_memories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='nominee',
            name='relationship',
            field=models.CharField(choices=[('spouse', 'Spouse'), ('child', 'Child'), ('parent', 'Parent'), ('sibling', 'Sibling'), ('friend', 'Friend'), ('other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vaultitem',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vault_items', to=settings.AUTH_USER_MODEL),
        ),
       migrations.AlterField(
            model_name='vaultitem',
            name='video_file',
            field=models.FileField(upload_to='vault_videos/', validators=[FYP_app.models.validate_file]),
        ),
        migrations.AlterUniqueTogether(
            name='credentials',
            unique_together={('user', 'platform')},
        ),
        migrations.AddField(
            model_name='user',
            name='dob',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Birth'),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10),
        ),
    ]
