# Generated by Django 6.0.2 on 2026-05-20 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FYP_app', '0002_alter_credentials_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default=' ', max_length=10),
        ),
    ]
