# Generated by Django 6.1 on 2026-08-20 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FYP_app', '0004_alter_credentials_password_alter_user_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='witness_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='witness_response_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
