# Generated by Django 6.1 on 2026-08-20 17:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FYP_app', '0005_userprofile_witness_confirmed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='witness_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
