# Generated by Django 6.1 on 2026-08-20 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FYP_app', '0006_userprofile_witness_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='credentials',
            name='is_sent',
            field=models.BooleanField(default=False),
        ),
    ]
