# Generated by Django 6.1 on 2026-08-21 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FYP_app', '0007_credentials_is_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmemory',
            name='accessible_to_nominees',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='credentials',
            name='status',
            field=models.CharField(choices=[('locked', 'Locked'), ('released', 'Released')], default='locked', max_length=20),
        ),
    ]
