# Generated by Django 6.1 on 2026-08-23 08:04

import FYP_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FYP_app', '0008_chatmemory_accessible_to_nominees_credentials_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vaultitem',
            name='video_file',
        ),
        migrations.AddField(
            model_name='vaultitem',
            name='file',
            field=models.FileField(default='', upload_to='vault_files/', validators=[FYP_app.models.validate_file]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vaultitem',
            name='last_sent_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vaultitem',
            name='recurring_interval_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vaultitem',
            name='release_type',
            field=models.CharField(choices=[('killswitch', 'Kill Switch (Inactivity)'), ('scheduled', 'Specific Date'), ('recurring', 'Recurring Date')], default='killswitch', max_length=20),
        ),
        migrations.AlterField(
            model_name='vaultitem',
            name='scheduled_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
