# Generated by Django 6.1 on 2026-08-25 04:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FYP_app', '0009_remove_vaultitem_video_file_vaultitem_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nominee',
            name='login_account',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nominee_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
