# Generated by Django 6.1 on 2026-08-26 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FYP_app', '0010_nominee_login_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('warning', 'Warning'), ('inactive', 'Inactive'), ('fallback', 'Fallback - Awaiting Nominee Confirmation')], default='active', max_length=10),
        ),
    ]
