# Generated by Django 6.1 on 2026-08-26 06:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FYP_app', '0011_alter_userprofile_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='nomineerole',
            name='vote',
            field=models.CharField(blank=True, choices=[('death', 'Confirmed Death'), ('alive', 'Confirmed Alive')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='nomineerole',
            name='vote_token',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True),
        ),
    ]
