# Generated by Django 6.1.1 on 2026-09-25 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FYP_app', '0004_alter_credentials_password_alter_user_gender_and_more'),
        ('FYP_app', '0012_nomineerole_vote_nomineerole_vote_token'),
    ]

    operations = [
    ]
