# Generated by Django 6.1.1 on 2026-09-25 17:02

import encrypted_model_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FYP_app', '0013_merge_20260925_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='released_at',
            field=models.DateTimeField(blank=True, help_text='When assets were released', null=True),
        ),
        migrations.AlterField(
            model_name='credentials',
            name='password',
            field=encrypted_model_fields.fields.EncryptedCharField(),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('warning', 'Warning'), ('inactive', 'Inactive'), ('fallback', 'Fallback - Awaiting Nominee Confirmation'), ('released', 'Released')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='timeout_days',
            field=models.PositiveIntegerField(default=7, help_text='Days of inactivity before warning triggers'),
        ),
    ]
